###   HDFC  BANK

### import tabula packages to extract table from pdf

In [1]:
from tabula import read_pdf
df=read_pdf("HDFC 5.pdf", pages="all")

/home/anuj/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/anuj/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

### print data frame

In [2]:
df

,Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance
0,04/04/18,CHQ PAID-MICR CTS-NO-ICICI CARD,0000000000001258,04/04/18,"22,600.00",NaN,"612,950.25"
1,05/04/18,RTGS CR-DEUT0784PBC-Q2AMEDIA SERVICES PV,DEUTR52018040598,05/04/18,NaN,"4,500,000.00","5,112,950.25"
2,NaN,T LTD-Q2A MEDIA SERVICES PVT LTD-DEUTR52,797840,NaN,NaN,NaN,NaN
3,NaN,018040598797840,NaN,NaN,NaN,NaN,NaN
4,05/04/18,EMI 48545156 CHQ S4854515619 04184854515,000000000000000,05/04/18,"20,517.00",NaN,"5,092,433.25"
5,NaN,6,NaN,NaN,NaN,NaN,NaN
6,06/04/18,CHQ PAID-MICR CTS-NO-TATA TELESERVICES L,0000000000001261,06/04/18,"24,750.00",NaN,"5,067,683.25"
7,06/04/18,CHQ PAID-MICR CTS-NO-TATA TELESERVICES L,0000000000001259,06/04/18,"100,000.00",NaN,"4,967,683.25"
8,06/04/18,CHQ PAID-MICR CTS-NO-TATA TELESERVICES,0000000000001260,06/04/18,"100,000.00",NaN,"4,867,683.25"
9,06/04/18,FT - CR - 03378190000100 - Q2A SERVICES,0000000000000945,06/04/18,NaN,"4,300,000.00","9,167,683.25"
10,NaN,PRIVATE LIMITED,NaN,NaN,NaN,NaN,NaN
11,06/04/18,SALARY- Q2AMEDIA SERVICES DR - 033729900,0000000000001245,06/04/18,"3,614,942.00",NaN,"5,552,741.25"
12,NaN,00042 - SALARY DUMMY A/C OKHLA BRANCH,NaN,NaN,NaN,NaN,NaN
13,06/04/18,SALARY- Q2AMEDIA SERVICES PVT LTD DR - 0,0000000000001244,06/04/18,"4,394,164.00",NaN,"1,158,577.25"
14,NaN,3372990000042 - SALARY DUMMY A/C OKHLA B,NaN,NaN,NaN,NaN,NaN
15,NaN,RANCH,NaN,NaN,NaN,NaN,NaN
16,07/04/18,FT - DR - 50100147486550 - RAGHVENDRA PR,0000000000001267,07/04/18,"58,290.00",NaN,"1,100,287.25"
17,NaN,ATAP SINGH,NaN,NaN,NaN,NaN,NaN
18,09/04/18,CHQ PAID-MICR CTS-NO-NEYAZUR RAHMAN,0000000000001265,09/04/18,"4,663.00",NaN,"1,095,624.25"
19,09/04/18,CHQ PAID-MICR CTS-NO-NUYAZUR,0000000000001262,09/04/18,"100,000.00",NaN,"995,624.25"
20,10/04/18,CHQ PAID-MICR CTS-NO-POONAM,0000000000001266,10/04/18,"24,970.00",NaN,"970,654.25"
21,10/04/18,CHQ PAID-MICR CTS-NO-ASHISH SRIVASTAVA,0000000000001263,10/04/18,"30,661.00",NaN,"939,993.25"
22,10/04/18,CHQ PAID-INWARD TRAN-SANTOSH KUMAR,0000000000001271,10/04/18,"12,577.00",NaN,"927,416.25"
23,11/04/18,490858716-EEPFOT,0000804119642148,11/04/18,"5,644.00",NaN,"921,772.25"
24,11/04/18,490860765-EEPFOT,0000804119647102,11/04/18,"565,778.00",NaN,"355,994.25"
25,11/04/18,LCH26212346418_ESIC-ESICCB,0000804119878811,11/04/18,"16,158.00",NaN,"339,836.25"
26,13/04/18,5329616300059454,0000804131644868,13/04/18,"150,000.00",NaN,"189,836.25"
27,13/04/18,CHQ PAID-TRANSFER IN-HDFC CARD 552260610,0000000000001273,13/04/18,"8,924.00",NaN,"180,912.25"
28,16/04/18,CHQ PAID-MICR CTS-NO-ANIL KUMAR,0000000000001270,16/04/18,"20,501.00",NaN,"160,411.25"
29,16/04/18,CHQ PAID-MICR CTS-NO-BIJOY KUMAR DEB,0000000000001269,16/04/18,"16,667.00",NaN,"143,744.25"
30,20/04/18,CHQ PAID-MICR CTS-NO-RANBAR ALI,0000000000001268,20/04/18,"15,207.00","128,537.25",NaN
31,23/04/18,CHQ PAID-TRANSFER IN-ARVIND KUMAR,0000000000001264,23/04/18,"26,577.00","101,960.25",NaN
32,24/04/18,RTGS CR-PUNB0272600-RTGS ASSTT COMM S TA,PUNBR52018042411,24/04/18,"710,414.00","812,374.25",NaN
33,NaN,X DIVN III NOID-MS Q2A MEDIA SERVICES PV,358893,NaN,NaN,NaN,NaN
34,NaN,T LTD-PUNBR52018042411358893,NaN,NaN,NaN,NaN,NaN
35,24/04/18,5329616300059454,0000804249162629,24/04/18,"100,000.00","712,374.25",NaN
36,24/04/18,5329730610295623,0000804249162873,24/04/18,"50,000.00","662,374.25",NaN
37,25/04/18,051007525041816679- CBDT TAX,000000000000000,25/04/18,"8,293.00","654,081.25",NaN
38,25/04/18,051007525041816680- CBDT TAX,000000000000000,25/04/18,"286,143.00","367,938.25",NaN
39,25/04/18,051007525041816682- CBDT TAX,000000000000000,25/04/18,"266,579.00","101,359.25",NaN
40,25/04/18,051007525041816683- CBDT TAX,000000000000000,25/04/18,"54,890.00","46,469.25",NaN
41,25/04/18,051007525041816684- CBDT TAX,000000000000000,25/04/18,"11,684.00","34,785.25",NaN
42,NaN,STATEMENT SUMMARY :-,NaN,NaN,NaN,NaN,NaN
43,NaN,Opening Balance,Dr Count,Cr Count,Debits Credits,Closing Bal,NaN
44,NaN,"635,550.25",29,3,"10,111,179.00 9,510,414.00","34,785.25",NaN
45,NaN,Generated On: 01-May-2018 11:36,Generated By: 62851349,NaN,Requesting Branch Code: NET,NaN,NaN
46,NaN,NaN,NaN,NaN,This is a computer generated statement and does,NaN,NaN
47,NaN,NaN,NaN,NaN,not require signature.,NaN,NaN

###  load another data of hdfc bank ( 16 pages) and extract table

In [3]:
from tabula import read_pdf
df3=read_pdf("HDFC 1.pdf", pages="all",multiple_tables=True)

In [4]:
df3

[           0                                         1                 2  \
 0       Date                                 Narration      Chq./Ref.No.
 1   05/04/17     EMI 38028301 CHQ S38028301/1-13 04/17   000000000000000
 2   06/04/17  RTGS CR-RATN0000999-RAVI METAL WORKS-DHE  RATNR52017040600
 3        NaN               ERAJ-RATNR52017040600523442            523442
 4   06/04/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000840083631A1
 5   07/04/17     ECS D-CMS ACH LIC NORTH-1273999170417  0000097581105283
 6   07/04/17     ECS D-CMS ACH LIC NORTH-1273999210417  0000097581105284
 7   12/04/17                  05857630000761 -TPT-BILL  00000904588127A1
 8   13/04/17  NEFT CR-UBIN0530760-J.P.ENTERPRISES-SHAM  0000SAA263985160
 9        NaN                    BHU IMPEX-SAA263985160               NaN
 10  13/04/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000915592029A1
 11  13/04/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000892517
 12  13/04/17               17172020000306 -TPT-PAYMENT  00000919448953A1
 13  15/04/17               17172020000306 -TPT-PAYMENT  00000929362072A1
 14  15/04/17           46990364-B-DHEERAJ KUMAR BANSAL  0000000111053480
 15  15/04/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000933941434A1
 16       NaN                                    PRISES               NaN
 17  15/04/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000933999076A1
 18  16/04/17               17172020000306 -TPT-PAYMENT  00000940897380A1
 19  17/04/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000948621273A1
 20  19/04/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000965085729A1
 21  20/04/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000000384
 22  24/04/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000005223805A1
 23       NaN                                    PRISES               NaN
 24  27/04/17  IMPS-711710253171-RAKESH RAJPUT-HDFC-XXX  0000711710253171
 25       NaN                   XXX8778-MB 50 K MNTU JI               NaN
 26  01/05/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000000388
 27  01/05/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000762541
 28  02/05/17                CHQ DEP RET- OTHER REASONS  0000000000762541
 29  04/05/17      EMI 46990364 CHQ S46990364/1-2 05/17   000000000000000
 30  05/05/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000130976192A1

            3                4             5                6
 0   Value Dt  Withdrawal Amt.  Deposit Amt.  Closing Balance
 1   05/04/17        52,736.00           NaN        93,915.89
 2   06/04/17              NaN    300,000.00       393,915.89
 3        NaN              NaN           NaN              NaN
 4   06/04/17       300,000.00           NaN        93,915.89
 5   07/04/17         5,889.00           NaN        88,026.89
 6   07/04/17         6,203.00           NaN        81,823.89
 7   12/04/17              NaN    100,000.00       181,823.89
 8   13/04/17              NaN     90,000.00       271,823.89
 9        NaN              NaN           NaN              NaN
 10  13/04/17       200,000.00           NaN        71,823.89
 11  15/04/17              NaN     46,200.00       118,023.89
 12  13/04/17              NaN     25,000.00       143,023.89
 13  15/04/17              NaN    100,000.00       243,023.89
 14  15/04/17              NaN    945,184.00     1,188,207.89
 15  15/04/17       150,000.00           NaN     1,038,207.89
 16       NaN              NaN           NaN              NaN
 17  15/04/17       400,000.00           NaN       638,207.89
 18  16/04/17              NaN     25,000.00       663,207.89
 19  17/04/17       300,000.00           NaN       363,207.89
 20  19/04/17       250,000.00           NaN       113,207.89
 21  21/04/17              NaN    150,000.00       263,207.89
 22  24/04/17       150,000.00           NaN       113,207.89
 23       NaN              NaN           NaN              NaN
 24  27/04/17              NaN     50,000.00       163,207.89
 25       NaN              NaN           NaN              NaN
 26  02/05/17              NaN    100,000.00       263,207.89
 27  02/05/17              NaN     70,000.00       333,207.89
 28  02/05/17        70,000.00           NaN       263,207.89
 29  04/05/17        69,086.00           NaN       194,121.89
 30  05/05/17       100,000.00           NaN        94,121.89  ,
            0                                         1                 2  \
 0   08/05/17     ECS D-CMS ACH LIC NORTH-1273999210517  0000128581070196
 1   08/05/17     ECS D-CMS ACH LIC NORTH-1273999170517  0000128581070198
 2   08/05/17  IMPS-712818613999-RAKESH RAJPUT-HDFC-XXX  0000712818613999
 3        NaN                   XXX8778-MB 50 K MNTU JI               NaN
 4   10/05/17               17172020000306 -TPT-PAYMENT  00000186483792A1
 5   10/05/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000188072091A1
 6   15/05/17   RTGS CR-ICIC0000104-GIRIRAJ WIRES CABLE  ICICR42017051500
 7        NaN    S-SHAMBHU IMPEX-ICICR42017051500410122            410122
 8   15/05/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000233504218A1
 9   16/05/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000000393
 10  18/05/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000260427714A1
 11       NaN                                    PRISES               NaN
 12  18/05/17  RTGS CR-KKBK0000958-SHARMA MANUFACTURING  KKBKR52017051800
 13       NaN   AND TRADING CO-SHAMBHU IMPEX-KKBKR52017            837878
 14       NaN                              051800837878               NaN
 15  18/05/17   16728970000071 -TPT-A ONE INTERNATIONAL  00000264592721A1
 16  19/05/17  NEFT DR-YESB0000184-CABLE TEL INDUSTRIES  N139170296484874
 17       NaN            -NETBANK, MUM-N139170296484874               NaN
 18  23/05/17      46990364-REFUND-DHEERAJ KUMAR BANSAL   000000000000000
 19  25/05/17               17172020000306 -TPT-PAYMENT  00000329425531A1
 20  27/05/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000351803965A1
 21       NaN                                    PRISES               NaN
 22  30/05/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000899637
 23  31/05/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000388286137A1
 24       NaN                                    PRISES               NaN
 25  02/06/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000762549
 26  05/06/17      EMI 46990364 CHQ S46990364/1-3 06/17   000000000000000
 27  05/06/17  NEFT CR-UBIN0530760-J.P.ENTERPRISES-SHAM  0000SAA275242659
 28       NaN                    BHU IMPEX-SAA275242659               NaN
 29  05/06/17   CHQ DEP - MICR - MICR 1 CLG - NOIDA WBO  0000000000000164
 30  06/06/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000471536936A1
 31       NaN                                    PRISES               NaN

            3           4           5             6
 0   08/05/17    6,203.00         NaN     87,918.89
 1   08/05/17    5,889.00         NaN     82,029.89
 2   08/05/17         NaN   50,000.00    132,029.89
 3        NaN         NaN         NaN           NaN
 4   10/05/17         NaN  150,000.00    282,029.89
 5   10/05/17  175,000.00         NaN    107,029.89
 6   15/05/17         NaN  200,000.00    307,029.89
 7        NaN         NaN         NaN           NaN
 8   15/05/17  200,000.00         NaN    107,029.89
 9   17/05/17         NaN  100,000.00    207,029.89
 10  18/05/17  100,000.00         NaN    107,029.89
 11       NaN         NaN         NaN           NaN
 12  18/05/17         NaN  900,000.00  1,007,029.89
 13       NaN         NaN         NaN           NaN
 14       NaN         NaN         NaN           NaN
 15  18/05/17  400,000.00         NaN    607,029.89
 16  19/05/17  500,000.00         NaN    107,029.89
 17       NaN         NaN         NaN           NaN
 18  23/05/17         NaN    9,013.98    116,043.87
 19  25/05/17         NaN  150,000.00    266,043.87
 20  27/05/17  100,000.00         NaN    166,043.87
 21       NaN         NaN         NaN           NaN
 22  31/05/17         NaN   71,505.00    237,548.87
 23  31/05/17   50,000.00         NaN    187,548.87
 24       NaN         NaN         NaN           NaN
 25  03/06/17         NaN   25,733.00    213,281.87
 26  05/06/17   69,086.00         NaN    144,195.87
 27  05/06/17         NaN   70,000.00    214,195.87
 28       NaN         NaN         NaN           NaN
 29  06/06/17         NaN  250,000.00    464,195.87
 30  06/06/17   78,202.00         NaN    385,993.87
 31       NaN         NaN         NaN           NaN  ,
            0                                         1                 2  \
 0   07/06/17     ECS D-CMS ACH LIC NORTH-1273999170617  0000158581050032
 1   07/06/17     ECS D-CMS ACH LIC NORTH-1273999210617  0000158581050033
 2   07/06/17  NEFT CR-UCBA0000240-BG INDUSTRIES-SHAMBH  0000SAA101887788
 3        NaN                      U IMPEX-SAA101887788               NaN
 4   13/06/17               17172020000306 -TPT-PAYMENT  00000547285739A1
 5   27/06/17   CHQ DEP - MICR - MICR 1 CLG - NOIDA WBO  0000000000000172
 6   29/06/17   50100074061075 -TPT-DHEERAJ KUMAR BANSA  00000694372659A1
 7        NaN                                         L               NaN
 8   01/07/17   50100074061075 -TPT-DHEERAJ KUMAR BANSA  00000721906556A1
 9        NaN                                         L               NaN
 10  03/07/17   50100074061075 -TPT-DHEERAJ KUMAR BANSA  00000743196317A1
 11       NaN                                         L               NaN
 12  03/07/17   50100074061075 -TPT-DHEERAJ KUMAR BANSA  00000753546154A1
 13       NaN                                         L               NaN
 14  04/07/17      EMI 46990364 CHQ S46990364/1-4 07/17   000000000000000
 15  05/07/17  IMPS-718609695023-J.P.ENTERPRISES-HDFC-X  0000718609695023
 16       NaN                  XXXXXXXXXX6310-50K_MNTU_               NaN
 17  07/07/17     ECS D-CMS ACH LIC NORTH-1273999170717  0000188581110245
 18  07/07/17     ECS D-CMS ACH LIC NORTH-1273999210717  0000188581110246
 19  10/07/17       ATW-498792XXXXXX1185-S1ACDH24-DELHI  0000000000004505
 20  10/07/17       ATW-498792XXXXXX1185-S1ACDH24-DELHI  0000000000004506
 21  15/07/17               17172020000306 -TPT-PAYMENT  00000883970785A1
 22  15/07/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000910844
 23  17/07/17  CHQ DEP MICR 08-MUM CLG - MICR CLG - MUM  0000000000282841
 24  18/07/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000907709545A1
 25  25/07/17  NEFT CR-UBIN0530760-J.P.ENTERPRISES-SHAM  0000SAA285723785
 26       NaN                    BHU IMPEX-SAA285723785               NaN
 27  25/07/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000969770301A1
 28  31/07/17                  05857630000761 -TPT-BILL  00000028871193A1
 29  31/07/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000029068141A1
 30  02/08/17  NEFT CR-IDIB000B027-MULTI OPERATIVE MEDI  IDIBH17214212883
 31       NaN  UM CABLES-SHAMBHU IMPEX-IDIBH17214212883               NaN

            3           4           5           6
 0   07/06/17    5,889.00         NaN  380,104.87
 1   07/06/17    6,203.00         NaN  373,901.87
 2   07/06/17         NaN  100,000.00  473,901.87
 3        NaN         NaN         NaN         NaN
 4   13/06/17         NaN  150,000.00  623,901.87
 5   28/06/17         NaN  300,000.00  923,901.87
 6   29/06/17   50,000.00         NaN  873,901.87
 7        NaN         NaN         NaN         NaN
 8   01/07/17   50,000.00         NaN  823,901.87
 9        NaN         NaN         NaN         NaN
 10  03/07/17  450,000.00         NaN  373,901.87
 11       NaN         NaN         NaN         NaN
 12  03/07/17  200,000.00         NaN  173,901.87
 13       NaN         NaN         NaN         NaN
 14  04/07/17   69,086.00         NaN  104,815.87
 15  05/07/17         NaN   50,000.00  154,815.87
 16       NaN         NaN         NaN         NaN
 17  07/07/17    5,911.00         NaN  148,904.87
 18  07/07/17    6,226.00         NaN  142,678.87
 19  10/07/17   15,000.00         NaN  127,678.87
 20  10/07/17   10,000.00         NaN  117,678.87
 21  15/07/17         NaN  150,000.00  267,678.87
 22  17/07/17         NaN   44,100.00  311,778.87
 23  18/07/17         NaN   50,000.00  361,778.87
 24  18/07/17  200,000.00         NaN  161,778.87
 25  25/07/17         NaN   60,000.00  221,778.87
 26       NaN         NaN         NaN         NaN
 27  25/07/17  100,000.00         NaN  121,778.87
 28  31/07/17         NaN  200,000.00  321,778.87
 29  31/07/17  200,000.00         NaN  121,778.87
 30  02/08/17         NaN   50,000.00  171,778.87
 31       NaN         NaN         NaN         NaN  ,
            0                                         1                 2  \
 0   03/08/17  NEFT CR-UCBA0000240-BG INDUSTRIES-SHAMBH  0000SAA106774349
 1        NaN                      U IMPEX-SAA106774349               NaN
 2   04/08/17  IMPS-721609914200-J.P.ENTERPRISES-HDFC-X  0000721609914200
 3        NaN                  XXXXXXXXXX6310-50K_MNTU_               NaN
 4   04/08/17      EMI 46990364 CHQ S46990364/1-5 08/17   000000000000000
 5   07/08/17     ECS D-CMS ACH LIC NORTH-1273999170817  0000219581065379
 6   07/08/17     ECS D-CMS ACH LIC NORTH-1273999210817  0000219581065380
 7   07/08/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000050032
 8   09/08/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000155516743A1
 9   09/08/17                   ECS C-VAT DEPTT.-438910  0000221372000124
 10  10/08/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000170736744A1
 11  11/08/17                   CHQ PAID - SHAHDARA, NE  0000000000000088
 12  11/08/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000910885
 13  19/08/17  IMPS-723109151485-RAKESH RAJPUT-HDFC-XXX  0000723109151485
 14       NaN          XXX8778-MB 50 K MONTU TR SHAMBHU               NaN
 15  19/08/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000140261
 16  22/08/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000271490430A1
 17       NaN                                    PRISES               NaN
 18  23/08/17   NEFT CR-BKDN0460060-R J TRADING-SHAMBHU  00000SDC65170798
 19       NaN                         IMPEX-SDC65170798               NaN
 20  23/08/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000287307490A1
 21       NaN                                    PRISES               NaN
 22  25/08/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000000148
 23  28/08/17               17172020000306 -TPT-PAYMENT  00000323636593A1
 24  29/08/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000329659117A1
 25       NaN                                    PRISES               NaN
 26  30/08/17                  50200002331629 -TPT-NEFT  00000342520126A1
 27  30/08/17   50200017074370 -TPT-GANPATI ENTERPRISES  00000342708468A1
 28  30/08/17  IMPS-724212101053-J.P.ENTERPRISES-HDFC-X  0000724212101053
 29       NaN                  XXXXXXXXXX6310-50K_MNTU_               NaN
 30  31/08/17  IMPS-724314157711-RAKESH RAJPUT-HDFC-XXX  0000724314157711
 31       NaN                    XXX8778-MB 50 K MNT TR               NaN

            3           4           5           6
 0   03/08/17         NaN   50,000.00  221,778.87
 1        NaN         NaN         NaN         NaN
 2   04/08/17         NaN   50,000.00  271,778.87
 3        NaN         NaN         NaN         NaN
 4   04/08/17   69,086.00         NaN  202,692.87
 5   07/08/17    5,911.00         NaN  196,781.87
 6   07/08/17    6,226.00         NaN  190,555.87
 7   08/08/17         NaN  144,432.00  334,987.87
 8   09/08/17  200,000.00         NaN  134,987.87
 9   09/08/17         NaN  208,138.00  343,125.87
 10  10/08/17  200,000.00         NaN  143,125.87
 11  11/08/17   40,000.00         NaN  103,125.87
 12  14/08/17         NaN   33,075.00  136,200.87
 13  19/08/17         NaN   50,000.00  186,200.87
 14       NaN         NaN         NaN         NaN
 15  21/08/17         NaN   30,444.00  216,644.87
 16  22/08/17  100,000.00         NaN  116,644.87
 17       NaN         NaN         NaN         NaN
 18  23/08/17         NaN   75,000.00  191,644.87
 19       NaN         NaN         NaN         NaN
 20  23/08/17   75,000.00         NaN  116,644.87
 21       NaN         NaN         NaN         NaN
 22  28/08/17         NaN  100,000.00  216,644.87
 23  28/08/17         NaN  300,000.00  516,644.87
 24  29/08/17  300,000.00         NaN  216,644.87
 25       NaN         NaN         NaN         NaN
 26  30/08/17         NaN  150,000.00  366,644.87
 27  30/08/17  250,000.00         NaN  116,644.87
 28  30/08/17         NaN   50,000.00  166,644.87
 29       NaN         NaN         NaN         NaN
 30  31/08/17         NaN   50,000.00  216,644.87
 31       NaN         NaN         NaN         NaN  ,
            0                                         1                 2  \
 0   31/08/17  NEFT CR-ICIC0000330-SHRI MOHAN CABLE CO-  0000000031713434
 1        NaN                SHAMBHU IMPEX-000031713434               NaN
 2   31/08/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000358769509A1
 3   01/09/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000140265
 4   04/09/17      EMI 46990364 CHQ S46990364/1-6 09/17   000000000000000
 5   05/09/17  RTGS CR-BARB0DURDEL-AJAY KUMAR BANSAL SO  BARBR52017090500
 6        NaN   N K BANSAL-SHAMBHU IMPEX-BARBR520170905            684550
 7        NaN                                  00684550               NaN
 8   05/09/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000421544421A1
 9        NaN                                    PRISES               NaN
 10  05/09/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000421558497A1
 11  07/09/17     ECS D-CMS ACH LIC NORTH-1273999170917  0000250581065557
 12  07/09/17     ECS D-CMS ACH LIC NORTH-1273999210917  0000250581065558
 13  11/09/17  FT - CR - 05852560001838 - B L METAL IND  0000000000000284
 14       NaN                                   USTRIES               NaN
 15  12/09/17  RTGS CR-IBKL0000170-MODERN INDUSTRIES-SH  IBKLR92017091200
 16       NaN        AMBHU IMPEX-IBKLR92017091200041677            041677
 17  13/09/17  NEFT DR-YESB0000184-CABLE TEL INDUSTRIES  N256170367283820
 18       NaN            -NETBANK, MUM-N256170367283820               NaN
 19  13/09/17  NEFT CR-UCBA0000240-BG INDUSTRIES-SHAMBH  0000SAA110332636
 20       NaN                      U IMPEX-SAA110332636               NaN
 21  13/09/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000512826151A1
 22  14/09/17  NEFT CR-SBIN0003989-R V ENTERPRISES-SHAM  SBIN417257700278
 23       NaN                BHU IMPEX-SBIN417257700278               NaN
 24  14/09/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000181179
 25  21/09/17                  50200002331629 -TPT-NEFT  00000583013473A1
 26  21/09/17   50200017074370 -TPT-GANPATI ELECTRONICS  00000585540033A1
 27  25/09/17  NEFT CR-IDIB000B027-MULTI OPERATIVE MEDI  IDIBH17268167124
 28       NaN  UM CABLES-SHAMBHU IMPEX-IDIBH17268167124               NaN
 29  25/09/17   50200009972505 -TPT-RADHEY RADHEY ENTER  00000618820639A1
 30       NaN                                    PRISES               NaN
 31  26/09/17  CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO  0000000000000226

            3           4           5           6
 0   31/08/17         NaN  160,981.00  377,625.87
 1        NaN         NaN         NaN         NaN
 2   31/08/17  260,000.00         NaN  117,625.87
 3   04/09/17         NaN   98,176.00  215,801.87
 4   04/09/17   69,086.00         NaN  146,715.87
 5   05/09/17         NaN  300,000.00  446,715.87
 6        NaN         NaN         NaN         NaN
 7        NaN         NaN         NaN         NaN
 8   05/09/17  100,000.00         NaN  346,715.87
 9        NaN         NaN         NaN         NaN
 10  05/09/17  200,000.00         NaN  146,715.87
 11  07/09/17    5,911.00         NaN  140,804.87
 12  07/09/17    6,226.00         NaN  134,578.87
 13  11/09/17         NaN   60,416.00  194,994.87
 14       NaN         NaN         NaN         NaN

### generate csv file and stored data of pdf into csv format

In [5]:
from tabula import convert_into

convert_into("HDFC 1.pdf", "test.csv", output_format="csv", pages="all",multiple_tables=True)
!cat test.csv

In [6]:
import pandas as pd 
data = pd.read_csv("test.csv", error_bad_lines=False)

b'Skipping line 224: expected 7 fields, saw 8\nSkipping line 225: expected 7 fields, saw 8\nSkipping line 226: expected 7 fields, saw 8\nSkipping line 227: expected 7 fields, saw 8\nSkipping line 228: expected 7 fields, saw 8\nSkipping line 229: expected 7 fields, saw 8\nSkipping line 230: expected 7 fields, saw 8\nSkipping line 231: expected 7 fields, saw 8\nSkipping line 232: expected 7 fields, saw 8\nSkipping line 233: expected 7 fields, saw 8\nSkipping line 234: expected 7 fields, saw 8\nSkipping line 235: expected 7 fields, saw 8\nSkipping line 236: expected 7 fields, saw 8\nSkipping line 237: expected 7 fields, saw 8\nSkipping line 238: expected 7 fields, saw 8\nSkipping line 239: expected 7 fields, saw 8\nSkipping line 240: expected 7 fields, saw 8\nSkipping line 241: expected 7 fields, saw 8\nSkipping line 242: expected 7 fields, saw 8\nSkipping line 243: expected 7 fields, saw 8\nSkipping line 244: expected 7 fields, saw 8\nSkipping line 245: expected 7 fields, saw 8\nSkipping line 246: expected 7 fields, saw 8\nSkipping line 247: expected 7 fields, saw 8\nSkipping line 248: expected 7 fields, saw 8\nSkipping line 249: expected 7 fields, saw 8\nSkipping line 250: expected 7 fields, saw 8\nSkipping line 251: expected 7 fields, saw 8\nSkipping line 252: expected 7 fields, saw 8\nSkipping line 253: expected 7 fields, saw 8\nSkipping line 254: expected 7 fields, saw 8\nSkipping line 255: expected 7 fields, saw 8\n'

### print data

In [7]:
data

,Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance
0,05/04/17,EMI 38028301 CHQ S38028301/1-13 04/17,000000000000000,05/04/17,"52,736.00",NaN,"93,915.89"
1,06/04/17,RTGS CR-RATN0000999-RAVI METAL WORKS-DHE,RATNR52017040600,06/04/17,NaN,"300,000.00","393,915.89"
2,NaN,ERAJ-RATNR52017040600523442,523442,NaN,NaN,NaN,NaN
3,06/04/17,16728970000071 -TPT-A ONE INTERNATIONAL,00000840083631A1,06/04/17,"300,000.00",NaN,"93,915.89"
4,07/04/17,ECS D-CMS ACH LIC NORTH-1273999170417,0000097581105283,07/04/17,"5,889.00",NaN,"88,026.89"
5,07/04/17,ECS D-CMS ACH LIC NORTH-1273999210417,0000097581105284,07/04/17,"6,203.00",NaN,"81,823.89"
6,12/04/17,05857630000761 -TPT-BILL,00000904588127A1,12/04/17,NaN,"100,000.00","181,823.89"
7,13/04/17,NEFT CR-UBIN0530760-J.P.ENTERPRISES-SHAM,0000SAA263985160,13/04/17,NaN,"90,000.00","271,823.89"
8,NaN,BHU IMPEX-SAA263985160,NaN,NaN,NaN,NaN,NaN
9,13/04/17,16728970000071 -TPT-A ONE INTERNATIONAL,00000915592029A1,13/04/17,"200,000.00",NaN,"71,823.89"
10,13/04/17,CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO,0000000000892517,15/04/17,NaN,"46,200.00","118,023.89"
11,13/04/17,17172020000306 -TPT-PAYMENT,00000919448953A1,13/04/17,NaN,"25,000.00","143,023.89"
12,15/04/17,17172020000306 -TPT-PAYMENT,00000929362072A1,15/04/17,NaN,"100,000.00","243,023.89"
13,15/04/17,46990364-B-DHEERAJ KUMAR BANSAL,0000000111053480,15/04/17,NaN,"945,184.00","1,188,207.89"
14,15/04/17,50200009972505 -TPT-RADHEY RADHEY ENTER,00000933941434A1,15/04/17,"150,000.00",NaN,"1,038,207.89"
15,NaN,PRISES,NaN,NaN,NaN,NaN,NaN
16,15/04/17,16728970000071 -TPT-A ONE INTERNATIONAL,00000933999076A1,15/04/17,"400,000.00",NaN,"638,207.89"
17,16/04/17,17172020000306 -TPT-PAYMENT,00000940897380A1,16/04/17,NaN,"25,000.00","663,207.89"
18,17/04/17,16728970000071 -TPT-A ONE INTERNATIONAL,00000948621273A1,17/04/17,"300,000.00",NaN,"363,207.89"
19,19/04/17,16728970000071 -TPT-A ONE INTERNATIONAL,00000965085729A1,19/04/17,"250,000.00",NaN,"113,207.89"
20,20/04/17,CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO,0000000000000384,21/04/17,NaN,"150,000.00","263,207.89"
21,24/04/17,50200009972505 -TPT-RADHEY RADHEY ENTER,00000005223805A1,24/04/17,"150,000.00",NaN,"113,207.89"
22,NaN,PRISES,NaN,NaN,NaN,NaN,NaN
23,27/04/17,IMPS-711710253171-RAKESH RAJPUT-HDFC-XXX,0000711710253171,27/04/17,NaN,"50,000.00","163,207.89"
24,NaN,XXX8778-MB 50 K MNTU JI,NaN,NaN,NaN,NaN,NaN
25,01/05/17,CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO,0000000000000388,02/05/17,NaN,"100,000.00","263,207.89"
26,01/05/17,CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO,0000000000762541,02/05/17,NaN,"70,000.00","333,207.89"
27,02/05/17,CHQ DEP RET- OTHER REASONS,0000000000762541,02/05/17,"70,000.00",NaN,"263,207.89"
28,04/05/17,EMI 46990364 CHQ S46990364/1-2 05/17,000000000000000,04/05/17,"69,086.00",NaN,"194,121.89"
29,05/05/17,16728970000071 -TPT-A ONE INTERNATIONAL,00000130976192A1,05/05/17,"100,000.00",NaN,"94,121.89"
...,...,...,...,...,...,...,...
426,27/03/18,NEFT CR-RATN0000999-RAVI METAL WORKS-DHE,0000000034398274,27/03/18,NaN,"300,000.00","602,269.87"
427,NaN,ERAJ-000034398274,NaN,NaN,NaN,NaN,NaN
428,27/03/18,CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO,0000000000188978,28/03/18,NaN,"70,800.00","673,069.87"
429,27/03/18,CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO,0000000000940613,28/03/18,NaN,"47,200.00","720,269.87"
430,27/03/18,"50200017074370 -TPT-GANPATI,SHAMBHU",00000099348592A1,27/03/18,"200,000.00",NaN,"520,269.87"
431,28/03/18,NEFT DR-YESB0000184-CABLE TEL INDUSTRIES,N087180504766521,28/03/18,"300,000.00",NaN,"220,269.87"
432,NaN,"-NETBANK, MUM-N087180504766521-CABLE TEL",NaN,NaN,NaN,NaN,NaN
433,NaN,",SHAMBHU",NaN,NaN,NaN,NaN,NaN
434,28/03/18,50200006848968 -TPT-PAYMENT,00000107518217A1,28/03/18,NaN,"33,143.00","253,412.87"
435,28/03/18,NEFT CR-PUNB0012500-STARLINE INDUSTRIES-,PUNBH18087340833,28/03/18,NaN,"27,435.00","280,847.87"
436,NaN,SHAMBHU IMPEX-PUNBH18087340833,NaN,NaN,NaN,NaN,NaN
437,29/03/18,50200006282982CA 2862,0000803297362874,29/03/18,NaN,"64,954.00","345,801.87"
438,29/03/18,POS 498792XXXXXX1185 PAYTM MALL POS DEBI,0000808870279585,29/03/18,"60,546.00",NaN,"285,255.87"
439,NaN,T,NaN,NaN,NaN,NaN,NaN
440,30/03/18,IMPS-808918309272-GANPATI AUTOTECH PRIVA,0000808918309272,30/03/18,"10,000.00",NaN,"275,255.87"
441,NaN,TE LIMITED-INDB-XXXXXXXX1953-SHAMBHU TO,NaN,NaN,NaN,NaN,NaN
442,NaN,GANPATI,NaN,NaN,NaN,NaN,NaN
443,30/03/18,REV-IMPS-808918309272-GANPATI AUTOTECH P,0000808918309272,30/03/18,NaN,"10,000.00","285,255.87"
444,NaN,RIVATE LIMITED-INDB-XXXXXXXX1953-SHAMBHU,NaN,NaN,NaN,NaN,NaN
445,NaN,TO GANPATI,NaN,NaN,NaN,NaN,NaN
446,31/03/18,IMPS-809012306733-GANPATI AUTOTECH PRIVA,0000809012306733,31/03/18,"10,000.00","275,255.87",NaN
447,NaN,"TE LIMITED-INDB-XXXXXXXX1953-GANPATI , S",NaN,NaN,NaN,NaN,NaN
448,NaN,HAMBHU,NaN,NaN,NaN,NaN,NaN
449,31/03/18,"CHQ PAID - SHAHDARA, NE",0000000000000100,31/03/18,"105,000.00","170,255.87",NaN
450,NaN,STATEMENT SUMMARY :-,NaN,NaN,NaN,NaN,NaN
451,NaN,Opening Balance,Dr Count,Cr Count,Debits Credits,Closing Bal,NaN
452,NaN,"146,651.89",146,172,"19,794,749.00 19,818,352.98","170,255.87",NaN
453,NaN,Generated On: 28-May-2018 12:31,Generated By: 57089318,NaN,Requesting Branch Code: NET,NaN,NaN
454,NaN,NaN,NaN,NaN,This is a computer generated statement and does,NaN,NaN
455,NaN,NaN,NaN,NaN,not require signature.,NaN,NaN

In [64]:

data1=data.dropna(subset = ['Date'])
data1.head()

,Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance
0,05/04/17,EMI 38028301 CHQ S38028301/1-13 04/17,000000000000000,05/04/17,"52,736.00",NaN,"93,915.89"
1,06/04/17,RTGS CR-RATN0000999-RAVI METAL WORKS-DHE,RATNR52017040600,06/04/17,NaN,"300,000.00","393,915.89"
3,06/04/17,16728970000071 -TPT-A ONE INTERNATIONAL,00000840083631A1,06/04/17,"300,000.00",NaN,"93,915.89"
4,07/04/17,ECS D-CMS ACH LIC NORTH-1273999170417,0000097581105283,07/04/17,"5,889.00",NaN,"88,026.89"
5,07/04/17,ECS D-CMS ACH LIC NORTH-1273999210417,0000097581105284,07/04/17,"6,203.00",NaN,"81,823.89"

In [9]:
import numpy as np

data2 = data1.replace(np.NaN, 0)

In [63]:
data2.head()

,Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance
0,2017-05-04,EMI 38028301 CHQ S38028301/1-13 04/17,000000000000000,05/04/17,52736.0,0.0,93915.89
1,2017-06-04,RTGS CR-RATN0000999-RAVI METAL WORKS-DHE,RATNR52017040600,06/04/17,0.0,300000.0,393915.89
3,2017-06-04,16728970000071 -TPT-A ONE INTERNATIONAL,00000840083631A1,06/04/17,300000.0,0.0,93915.89
4,2017-07-04,ECS D-CMS ACH LIC NORTH-1273999170417,0000097581105283,07/04/17,5889.0,0.0,88026.89
5,2017-07-04,ECS D-CMS ACH LIC NORTH-1273999210417,0000097581105284,07/04/17,6203.0,0.0,81823.89

In [11]:
data2.describe(include='all')

,Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance
count,299,299,299,299,299,299,299
unique,164,134,284,161,45,82,268
top,09/02/18,CHQ DEP MICR CLG NOIDA - MICR 1 CLG - NO,000000000000000,28/03/18,0,0,"216,644.87"
freq,5,51,14,5,160,137,4

In [12]:
data2.dtypes

Date               object
Narration          object
Chq./Ref.No.       object
Value Dt           object
Withdrawal Amt.    object
Deposit Amt.       object
Closing Balance    object
dtype: object

In [13]:
data2['Deposit Amt.'] = data2['Deposit Amt.'].str.replace(',', '')
data2['Withdrawal Amt.'] = data2['Withdrawal Amt.'].str.replace(',', '')
data2['Closing Balance'] = data2['Closing Balance'].str.replace(',', '')

In [14]:
data2['Withdrawal Amt.']=data2['Withdrawal Amt.'].astype(float)
data2['Deposit Amt.']=data2['Deposit Amt.'].astype(float)
data2['Closing Balance']=data2['Closing Balance'].astype(float)

In [15]:
data2.describe()

       Withdrawal Amt.   Deposit Amt.  Closing Balance
count       139.000000     162.000000     2.970000e+02
mean     132408.266187  116509.782222     2.651534e+05
std      121763.467045  128082.499275     1.709194e+05
min        2350.000000      10.000000     7.182389e+04
25%       21868.500000   50000.000000     1.489049e+05
50%      100000.000000   70000.000000     2.166449e+05
75%      200000.000000  150000.000000     3.332079e+05
max      500000.000000  945184.000000     1.188208e+06

In [16]:
import pandas as pd
data2['Date']=pd.to_datetime(data2['Date'])

In [17]:
data2 = data2.replace(np.NaN, 0)

# metadata of pdf

In [62]:
 from pdfrw import PdfReader
 
def get_pdf_info(path):
    pdf = PdfReader(path)
    
    print(pdf.keys())
    print(pdf.Info)      
    print(pdf.Root.keys())
    print('PDF has {} pages'.format(len(pdf.pages)))
    f = open("HDFC_1.txt","a")
    f.write(f'{pdf.Info}')
    
    
 
if __name__ == '__main__':
    get_pdf_info('HDFC10.pdf')
    get_pdf_info('HDFC25.pdf')

['/Size', '/Root', '/Info', '/ID']
{'/Producer': '(GPL Ghostscript 9.07)', '/CreationDate': "(D:20180816121048+05'30')", '/ModDate': "(D:20180816121048+05'30')", '/Title': '(Sriram Khattar_16_08_2018_12_00_18)', '/Creator': '(Adobe Acrobat 15.6.0)', '/Author': '()'}
['/Type', '/Pages', '/PageLabels', '/Metadata']
PDF has 3 pages
['/Root', '/Info', '/Size']
{'/Title': '<FEFF005000440046002000460069006C0065>', '/Author': '<FEFF00410044004D0049004E>', '/Creator': '<FEFF005000440046002000460069006C0065>', '/Producer': '<FEFF0064006F00500044004600200020002000560065007200200036002E00310020004200750069006C006400200032003600390020002800570069006E0064006F00770073002000560069007300740061002000200078003600340029>', '/CreationDate': '(D:20180913083450)'}
['/Type', '/Pages', '/PageLayout', '/PageMode']
PDF has 14 pages